// SPDX-FileCopyrightText: 2026 The eepview contributors
// SPDX-License-Identifier: MIT

//! Build script: Tauri code generation, and one permission per IPC command, so the
//! capabilities in `capabilities/` decide which webviews may call each one.

/// Every IPC command of `docs/wiki/ipc-contract.md`.
const COMMANDS: &[&str] = &[
    "tab_new",
    "tab_close",
    "tab_select",
    "tab_move",
    "tab_list",
    "navigate",
    "go_back",
    "go_forward",
    "reload",
    "stop",
    "home",
    "find",
    "find_close",
    "zoom_in",
    "zoom_out",
    "zoom_reset",
    "site_js_set",
    "bookmarks_list",
    "bookmark_add",
    "bookmark_update",
    "bookmark_remove",
    "bookmark_find",
    "bookmarks_export",
    "bookmarks_export_file",
    "bookmarks_import",
    "history_query",
    "history_remove",
    "history_clear",
    "suggest",
    "settings_get",
    "settings_set",
    "router_status",
    "router_stats",
    "connection_pause",
    "connection_resume",
    "router_control",
    "chrome_set_height",
    "platform",
    "chrome_insets",
    "window_fullscreen",
    "popup_open",
    "popup_size",
    "popup_close",
    "report_preview",
    "report_open",
    "diag_crash_status",
    "diag_crash_dismiss",
    "diag_logs_delete",
];

/// The short git commit, for the report (`EEPVIEW_COMMIT`); `unknown` outside a git tree.
fn commit() -> String {
    std::process::Command::new("git")
        .args(["rev-parse", "--short=12", "HEAD"])
        .output()
        .ok()
        .filter(|o| o.status.success())
        .and_then(|o| String::from_utf8(o.stdout).ok())
        .map(|s| s.trim().to_owned())
        .filter(|s| !s.is_empty() && s.bytes().all(|b| b.is_ascii_hexdigit()))
        .unwrap_or_else(|| "unknown".to_owned())
}

/// The basenames of every `.rs` file under `dir`, recursively.
fn rust_names(dir: &std::path::Path, out: &mut std::collections::BTreeSet<String>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for path in entries.flatten().map(|e| e.path()) {
        if path.is_dir() {
            rust_names(&path, out);
        } else if path.extension().is_some_and(|e| e == "rs") {
            out.extend(path.file_name().and_then(|n| n.to_str()).map(str::to_owned));
        }
    }
}

/// Writes `SOURCE_FILES`: the basenames of eepview's own Rust files, the closed list a panic
/// location may name (docs/wiki/diagnostics-and-bug-reports.md, R1.6).
fn source_files() {
    let mut names = std::collections::BTreeSet::new();
    rust_names(std::path::Path::new("src"), &mut names);
    if let Ok(crates) = std::fs::read_dir("crates") {
        for krate in crates.flatten() {
            rust_names(&krate.path().join("src"), &mut names);
        }
    }
    let list: Vec<String> = names.iter().map(|n| format!("{n:?}")).collect();
    let code = format!(
        "/// The basenames of eepview's own `.rs` files, sorted (generated by `build.rs`).\n\
         pub const SOURCE_FILES: &[&str] = &[{}];\n",
        list.join(", ")
    );
    let out = std::path::PathBuf::from(std::env::var("OUT_DIR").unwrap_or_default());
    if let Err(error) = std::fs::write(out.join("source_files.rs"), code) {
        eprintln!("source list not written: {error}");
        std::process::exit(1);
    }
    println!("cargo:rerun-if-changed=src");
    println!("cargo:rerun-if-changed=crates");
}

fn main() {
    source_files();
    println!("cargo:rustc-env=EEPVIEW_COMMIT={}", commit());
    println!("cargo:rerun-if-changed=../.git/HEAD");
    let manifest = tauri_build::AppManifest::new().commands(COMMANDS);
    // tauri-build would embed the Windows manifest into the app binary only; test binaries
    // then fail to start (STATUS_ENTRYPOINT_NOT_FOUND). Embed one manifest everywhere.
    let windows = tauri_build::WindowsAttributes::new_without_app_manifest();
    let attributes = tauri_build::Attributes::new()
        .app_manifest(manifest)
        .windows_attributes(windows);
    embed_windows_manifest();
    if let Err(error) = tauri_build::try_build(attributes) {
        eprintln!("tauri build failed: {error:#}");
        std::process::exit(1);
    }
}

/// Links `windows-app-manifest.xml` into every MSVC executable of the crate, tests included.
fn embed_windows_manifest() {
    let target = std::env::var("TARGET").unwrap_or_default();
    if !target.ends_with("windows-msvc") {
        return;
    }
    let dir = std::env::var("CARGO_MANIFEST_DIR").unwrap_or_default();
    let manifest = std::path::Path::new(&dir).join("windows-app-manifest.xml");
    println!("cargo:rerun-if-changed=windows-app-manifest.xml");
    println!("cargo:rustc-link-arg=/MANIFEST:EMBED");
    println!("cargo:rustc-link-arg=/MANIFESTINPUT:{}", manifest.display());
}
