#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 The eepview contributors
# SPDX-License-Identifier: MIT
# Print CHANGELOG.md, generated by git-cliff from the Conventional Commit titles.
# Usage: scripts/changelog.sh [revision]   # prints to stdout, revision defaults to HEAD
#        scripts/changelog.sh --write [revision]   # rewrites CHANGELOG.md, revision defaults to HEAD
# In a PR, run `scripts/changelog.sh --write origin/main`: docs-check compares the file with the output for the base branch.
# Needs git-cliff on PATH. CI installs the pinned version with scripts/install-git-cliff.sh.
set -euo pipefail

cd "$(dirname "$0")/.."

if ! command -v git-cliff >/dev/null 2>&1; then
  echo "error: git-cliff is not installed. Run 'brew install git-cliff' or scripts/install-git-cliff.sh <dir>." >&2
  exit 1
fi

if [ "${1:-}" = "--write" ]; then
  git-cliff --config cliff.toml --output CHANGELOG.md "$(git rev-parse "${2:-HEAD}")"
else
  git-cliff --config cliff.toml "$(git rev-parse "${1:-HEAD}")"
fi
